name: Debug Secrets

on:
  workflow_dispatch: # 수동 실행

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Check secrets
        run: |
          echo "ZERO_GITHUB_KEY exists: ${{ secrets.ZERO_GITHUB_KEY != '' }}"
          echo "ZERO_ACCOUNT_EMAIL exists: ${{ secrets.ZERO_ACCOUNT_EMAIL != '' }}"
          echo "ZERO_GITHUB_KEY length: ${#ZERO_GITHUB_KEY}"
          echo "ZERO_ACCOUNT_EMAIL: $ZERO_ACCOUNT_EMAIL"
        env:
          ZERO_GITHUB_KEY: ${{ secrets.ZERO_GITHUB_KEY }}
          ZERO_ACCOUNT_EMAIL: ${{ secrets.ZERO_ACCOUNT_EMAIL }}
