name: Sync to Forked Repository for Development Environment

on:
  push:
    branches: [dev] # 조직 레포 dev 브랜치 업데이트 시 포크 레포 dev와 동기화하여 개발 환경 배포

jobs:
  sync-to-fork-for-development:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout organization repository dev branch
        uses: actions/checkout@v4

      - name: Remove .github directory # CI/CD not needed in deploy repo
        run: rm -rf .github

      - name: Debug sync action parameters
        run: |
          echo "=== Sync Action Debug Info ==="
          echo "Source repository: ${{ github.repository }}"
          echo "Source branch: ${{ github.ref_name }}"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Commit message: ${{ github.event.commits[0].message }}"
          echo "Destination: 0zuth/OneByOne_FE"
          echo "Target branch: dev"
          echo "Action version: actions/checkout@v4 + manual git operations"
          echo "Create branch if needed: true"
          echo "================================"

      - name: Check current directory structure
        run: |
          echo "=== Current Directory Structure ==="
          ls -la
          echo "================================"

      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ZERO_GITHUB_KEY }}
          repository: 0zuth/OneByOne_FE
          path: target-repo
          ref: dev
          fetch-depth: 0

      - name: Copy files to target repository
        run: |
          cp -r . target-repo/
          cd target-repo
          git config --global user.name "0zuth"
          git config --global user.email "${{ secrets.ZERO_ACCOUNT_EMAIL }}"
          git config --global init.defaultBranch dev
          git add -A
          git status
          git commit -m "${{ github.event.commits[0].message }}" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.ZERO_GITHUB_KEY }}@github.com/0zuth/OneByOne_FE.git dev
        env:
          GIT_AUTHOR_NAME: "0zuth"
          GIT_AUTHOR_EMAIL: "${{ secrets.ZERO_ACCOUNT_EMAIL }}"
          GIT_COMMITTER_NAME: "0zuth"
          GIT_COMMITTER_EMAIL: "${{ secrets.ZERO_ACCOUNT_EMAIL }}"
        continue-on-error: true

      - name: Check sync result
        if: failure()
        run: |
          echo "❌ Sync action failed!"
          echo "Check the logs above for detailed error information."
          echo "Common issues:"
          echo "1. Target repository doesn't exist"
          echo "2. Insufficient permissions to push to target repository"
          echo "3. Target branch is protected"
          echo "4. Network connectivity issues"
          echo "5. Action version compatibility issues"
          exit 1

      - name: Confirm successful sync to forked repository dev branch
        if: success()
        run: echo "✅ Successfully synced to forked repository dev branch (0zuth/OneByOne_FE)"
