name: Sync to Forked Repository for Production Deployment

on:
  push:
    branches: [main] # 조직 레포 main 브랜치 업데이트 시 포크 레포와 동기화하여 프로덕션 배포

jobs:
  sync-to-fork-for-production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout organization repository main branch
        uses: actions/checkout@v4

      - name: Remove .github directory # CI/CD not needed in deploy repo
        run: rm -rf .github

      - name: Debug sync action parameters
        run: |
          echo "=== Sync Action Debug Info ==="
          echo "Source repository: ${{ github.repository }}"
          echo "Source branch: ${{ github.ref_name }}"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Commit message: ${{ github.event.commits[0].message }}"
          echo "Destination: 0zuth/OneByOne_FE"
          echo "Target branch: main"
          echo "Action version: actions/checkout@v4 + manual git operations"
          echo "Create branch if needed: true"
          echo "================================"

      - name: Check current directory structure
        run: |
          echo "=== Current Directory Structure ==="
          ls -la
          echo "================================"

      - name: Clone target repository
        run: |
          git clone https://x-access-token:${{ secrets.ZERO_GITHUB_KEY }}@github.com/0zuth/OneByOne_FE.git target-repo
          cd target-repo
          git config user.name "0zuth"
          git config user.email "${{ secrets.ZERO_ACCOUNT_EMAIL }}"

      - name: Copy files to target repository
        run: |
          cp -r . target-repo/
          cd target-repo
          git add -A
          git status
          git commit -m "${{ github.event.commits[0].message }}" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.ZERO_GITHUB_KEY }}@github.com/0zuth/OneByOne_FE.git main
        env:
          GIT_AUTHOR_NAME: "0zuth"
          GIT_AUTHOR_EMAIL: "${{ secrets.ZERO_ACCOUNT_EMAIL }}"
          GIT_COMMITTER_NAME: "0zuth"
          GIT_COMMITTER_EMAIL: "${{ secrets.ZERO_ACCOUNT_EMAIL }}"
        continue-on-error: true

      - name: Check sync result
        if: failure()
        run: |
          echo "❌ Sync action failed!"
          echo "Check the logs above for detailed error information."
          echo "Common issues:"
          echo "1. Target repository doesn't exist"
          echo "2. Insufficient permissions to push to target repository"
          echo "3. Target branch is protected"
          echo "4. Network connectivity issues"
          echo "5. Action version compatibility issues"
          exit 1

      - name: Confirm successful sync to forked repository for production deployment
        if: success()
        run: echo "✅ Successfully synced to forked repository main branch (0zuth/OneByOne_FE)"
